[package]
name = "dft_tx_storage"
version = "0.3.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
dft_types = { path = "../dft_types" }
dft_utils = { path = "../dft_utils" }
ic-cdk = "0.4.0"
ic-cdk-macros = "0.4.0"
candid = "0.7.11"
serde = "1.0.135"

[dev-dependencies]
rstest = "0.12.0"
